name: 'Jira Label Action'
description: 'Labels a PR based on JIRA ticket type'
inputs:
  jira-url:
    description: 'jira rest api url'
    required: true
  jira-username:
    description: 'jira username'
    required: true
  jira-token:
    description: 'jira api token'
    required: true
  repo-token:
    description: 'github repo token'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
