name: 'Jira Label Action'
description: 'Labels a PR based on JIRA ticket type'
inputs:
  repo-token:
    description: 'github repo token'
    required: true
  ticket-regex:
    description: 'regex for matching JIRA ticket id'
    required: true
  jira-url:
    description: 'jira rest api url'
    required: true
  jira-username:
    description: 'jira username'
    required: true
  jira-token:
    description: 'jira api token'
    required: true
  configuration-path:
    description: 'The path for the label configurations'
    default: '.github/jira-ticket-labeler.yml'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
