on: [pull_request]
jobs:
  apply_jira_label:
    runs-on: ubuntu-latest
    name: Adds PR label based on JIRA ticket type
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: JIRA Label Action
        id: jira
        uses: hometeam/jira-label-action@master
